env:
  - COVERAGE=1
language: ruby
rvm:
  - 2.1.5
  - 2.2.3
  - 2.3.0
  - jruby-head

before_install:
  # bundler installation needed for jruby-head
  #  https://github.com/travis-ci/travis-ci/issues/5861
  - gem install bundler
